# -*- coding: utf-8 -*-
"""PAC_Project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-y_iBGUgRM57kKDeQfcG4R18246r3oOu
"""

# from google.colab import drive
# drive.mount('/content/drive')

### import important libraries
import os
import networkx as nx
import numpy as np
import argparse
import pwd

### text colors
RED = "\033[31m"
GREEN = "\033[32m"
RESET = "\033[0m"


### Declare two graphs
# G1 = nx.read_edgelist(file_path+'//'+'seed_G1.edgelist')
# G2 = nx.read_edgelist(file_path+'//'+'seed_G2.edgelist')



# ### separate seed nodes of two graphs
# seed_pair_list = list()
# seed_nodes_G1 = dict()
# seed_nodes_G2 = dict()

# with open(file_path+'//'+"seed_mapping.txt", 'r') as seed_mapping_file:
#     for line in seed_mapping_file:
#         line_data = line.rstrip('\n')
#         line_data = tuple(line_data.split(' '))
#         # print(line_data)
#         seed_pair_list.append(line_data)
#         seed_nodes_G1[line_data[0]] = line_data[1]
#         seed_nodes_G2[line_data[1]] = line_data[0]



class SeedFreeD: 
    def __init__(self, Graph1, Graph2, seed_pair_list, ecce_threshold):
        self.G1 = Graph1
        self.G2 = Graph2
        
        ### ECCE Threshold 
        self.ecce_threshold = ecce_threshold
   
        self.seed_pair_list = seed_pair_list
        
        self.seed_nodes_G1 = dict()
        self.seed_nodes_G2 = dict()

        for u, v in self.seed_pair_list:
            self.seed_nodes_G1[u] = v
            self.seed_nodes_G2[v] = u
    
        print(f" seed nodes in graph 1: {len(self.seed_nodes_G1)} \
        \n seed nodes in graph 2: {len(self.seed_nodes_G2)} \n")
    ### set-get 
    def set_new_GraphStatus(self, seed_nodes_G1, seed_nodes_G2, seed_pair_list):
        
        self.seed_nodes_G1 = seed_nodes_G1
        self.seed_nodes_G2 = seed_nodes_G2
        self.seed_pair_list = seed_pair_list
        
    ### The score function
    
    def calculate_score_G1_to_G2(self, G_n_tuple_G1, G_n_tuple_G2, num_of_comm_seed_pairs):
        G1, u = G_n_tuple_G1
        G2, v = G_n_tuple_G2
    
        score = num_of_comm_seed_pairs / (np.sqrt(len(G1[u]))*np.sqrt(len(G2[v])))
    
        return u, v, score
    
    ### Find nodes for operation those are connected with at least one seed node
    
    def find_nodes_seed_dictionary(self):
    
        ### separate nodes those are not included in the seed list
    
        unseed_nodes_G1 = list(set(list(self.G1.nodes())) - set( list( self.seed_nodes_G1.keys() )) )
        unseed_nodes_G2 = list(set(list(self.G2.nodes())) - set( list( self.seed_nodes_G2.keys() )) )
    
        # print(len(G1.nodes()), len(unseed_nodes_G1), len(G2.nodes()), len(unseed_nodes_G2))
    
        ### Separate those nodes which will be tested for find out the new seed pairs
        seed_nodes_neighbors_G1 = list()
        seed_nodes_neighbors_G2 = list()
    
        for u, v in self.seed_pair_list:
            
            if u in self.G1.nodes() and v in self.G2.nodes():
                seed_nodes_neighbors_G1.extend(list(self.G1[u]))
                seed_nodes_neighbors_G2.extend(list(self.G2[v]))
            else:
                continue
    
        ### Find experimentable nodes
        experiment_nodes_G1 = list(set(unseed_nodes_G1).intersection(set(seed_nodes_neighbors_G1)))
        experiment_nodes_G2 = list(set(unseed_nodes_G2).intersection(set(seed_nodes_neighbors_G2)))
    
        ### Find experimental nodes seed dictionary
        experiments_nodes_seed_dictionary_G1 = dict()
        experiments_nodes_seed_dictionary_G2 = dict()
    
        for node in experiment_nodes_G1:
    
            seed_neighbors_set = set(self.seed_nodes_G1).intersection( set(list(self.G1[node])) )
    
            if len(seed_neighbors_set) > 0:
                experiments_nodes_seed_dictionary_G1[node] = seed_neighbors_set
    
        for node in experiment_nodes_G2:
    
            seed_neighbors_set = set(self.seed_nodes_G2).intersection( set(list(self.G2[node])) )
    
            if len(seed_neighbors_set) > 0:
                experiments_nodes_seed_dictionary_G2[node] = seed_neighbors_set
            # print(node, experiments_nodes_seed_dictionary_G1[node])
        # experiments_nodes_seed_dictionary_G1
    
        return experiment_nodes_G1, experiment_nodes_G2, \
        experiments_nodes_seed_dictionary_G1, experiments_nodes_seed_dictionary_G2
    
    ### Do Operation for seed-based de-annonymization
    
    def operation(self):
    
        experiment_nodes_G1, experiment_nodes_G2, \
        experiments_nodes_seed_dictionary_G1, \
        experiments_nodes_seed_dictionary_G2 = self.find_nodes_seed_dictionary()
    
        ### New added pairs preserves the newly included seed pairs
        new_added_pairs = dict()
        new_seed_nodes_G1 = dict() 
        new_seed_nodes_G2 = dict() 
        
        # ECCE_threshold = 0.25
    
        ### Do operation for each experiment node
        for key in experiments_nodes_seed_dictionary_G1.keys():
    
            visited_pair_node_G2 = set()
            score_dictionary = dict()
    
            seed_nodes_under_u = experiments_nodes_seed_dictionary_G1[key]
    
            ### Do experiment on the connected seed nodes with the experiment node
            for n in experiments_nodes_seed_dictionary_G1[key]:
    
                ### G2[seed_nodes_G1[n]] get the seed pair from graph G2
                potential_pairs_list = set( list( self.G2[self.seed_nodes_G1[n]] )).intersection(set(experiment_nodes_G2)) - (set(visited_pair_node_G2))
    
                # print(len(potential_pairs_list), end=", ")
                visited_pair_node_G2 = visited_pair_node_G2.union(potential_pairs_list)
    
                ### pp_node: potential pair node
                for pp_node in potential_pairs_list:
                    G_n_tuple_G1 = (self.G1, key)
                    G_n_tuple_G2 = (self.G2, pp_node)
    
                    seed_nodes_under_v = experiments_nodes_seed_dictionary_G2[pp_node]
                    opposite_seed_pair_list_u = [self.seed_nodes_G1[nd] for nd in seed_nodes_under_u]
                    common_seed_pairs = set(seed_nodes_under_v).intersection(set(opposite_seed_pair_list_u))
    
                    ### calculate the score
                    u, v, score = self.calculate_score_G1_to_G2(G_n_tuple_G1, G_n_tuple_G2, len(common_seed_pairs))
                    score_dictionary[v] = score
    
            ### measure the Eccentricity
            values = list(score_dictionary.values())
    
            ECCE = 0
            S_max = 0
    
            if len(values) >= 2:
                
                top_2 = sorted(values, reverse= True)
                S_max = top_2[0]# max(values)
                S_max2 = top_2[1]# max(v for v in values if v != S_max)
    
                std_dev = np.std(values)
    
                if std_dev != 0:
                    ECCE = (S_max - S_max2)/std_dev
    
            
            # filtered_score_dictionary = {k:v for k, v in score_dictionary.items() if v > ECCE}
    
            if len(score_dictionary) > 0 and ECCE >= self.ecce_threshold:
                # print(f"Info: {ECCE}, {len(filtered_score_dictionary)}, {len(values)}")
                # if ECCE > ECCE_threshold:
                # filtered_score_dictionary = {k:v for k, v in score_dictionary.items() if v > ECCE}
    
                ### select the maximum scored node from graph 2 as seed pair
                max_key = max(score_dictionary, key = score_dictionary.get)
    
                if key not in new_seed_nodes_G1 and max_key not in new_seed_nodes_G2:
    
                    tup = (key, max_key)
                    self.seed_pair_list.append(tup)
                    new_seed_nodes_G1[key] = max_key
                    new_seed_nodes_G2[max_key] = key
                    # seed_nodes_G1[key] = max_key
                    # seed_nodes_G2[max_key] = key
                    new_added_pairs[(key, max_key)] = S_max
                    print(f"{GREEN}A new Pair has been added: ({key}, {max_key}):{new_added_pairs[(key, max_key)]}{RESET}")
    
                elif max_key in new_seed_nodes_G2:
    
                    deletable_tuple = (new_seed_nodes_G2[max_key], max_key)
    
                    if new_added_pairs[deletable_tuple] < S_max:
    
                        print(f"{RED}A Pair is going to be deleted for {max_key}: ({new_seed_nodes_G2[max_key]},{max_key}):{new_added_pairs[deletable_tuple]}{RESET}")
                        # seed_pair_list.remove(deletable_tuple)
                        
                        del new_added_pairs[deletable_tuple]
                        del new_seed_nodes_G1[new_seed_nodes_G2[max_key]]
                        del new_seed_nodes_G2[max_key]
    
    
                        new_seed_nodes_G1[key] = max_key
                        new_seed_nodes_G2[max_key] = key
                        tup = (key, max_key)
                        self.seed_pair_list.append(tup)
                        new_added_pairs[tup] = S_max
                        print(f"{GREEN}A new Pair has been added: ({key}, {max_key}):{new_added_pairs[(key, max_key)]}{RESET}")
                        # print(new_added_pairs[(key, max_key)],'---')
                    
        for new_u, new_v in new_added_pairs.keys(): 
            
            self.seed_nodes_G1[new_u] = new_v
            self.seed_nodes_G2[new_v] = new_u
            self.seed_pair_list.append((new_u, new_v))
            
        return new_added_pairs, self.seed_nodes_G1, self.seed_nodes_G2, self.seed_pair_list
    
    def iterativeOperation(self): 
        
        new_seed_pairs = list()
        new_added_pairs, seed_nodes_G1, seed_nodes_G2, training_seed_pair_list = self.operation()
        new_seed_pairs.extend(list(new_added_pairs.keys()))
        print(f"Number of Newly added Pairs: {len(new_added_pairs)}")
        
        while len(new_added_pairs) > 0:
            self.set_new_GraphStatus(seed_nodes_G1, seed_nodes_G2, training_seed_pair_list)
            new_added_pairs, seed_nodes_G1, seed_nodes_G2, training_seed_pair_list = self.operation()
            new_seed_pairs.extend(list(new_added_pairs.keys()))
            print(f"Number of Newly added Pairs: {len(new_added_pairs)}")
            
        return new_seed_pairs, seed_nodes_G1


def process_files_and_get_initial_data(file_path, train_portion = 0.20):
    
    print(file_path)
    # files = os.listdir(file_path)
    # files = sorted(files)
    
    # files
    validation_pair_file = None
    validation_pair_list = list()
    
    ### Declare two graphs
    G1 = None
    G2 = None 
    
    if 'validation_Dataset' in file_path:
        ### Declare two graphs
        files = os.listdir(file_path)
 
        for file in files:
            # print(file)
            if 'G1.edgelist' in file:
                G1 = nx.read_edgelist(file_path+'//'+ file)
            elif 'G2.edgelist' in file:
                G2 = nx.read_edgelist(file_path+'//'+ file)
            elif 'mapping' in file: 
                validation_pair_file = file 
            
    with open(file_path+'//'+ validation_pair_file, 'r') as seed_mapping_file:
        for line in seed_mapping_file:
            line_data = line.rstrip('\n')
            line_data = tuple(line_data.split(' '))
            
            u, v = line_data
            
            if u in G1 and u in G2:
                validation_pair_list.append(line_data)
            # print(line_data)
    
    ### Training nodes % = 10%
    train_portion = train_portion
    split_index = int(len(validation_pair_list) * train_portion)
    
    training_seed_pair_list = validation_pair_list[:split_index]
    test_seed_pair_list = validation_pair_list[split_index:]
    
    print(f" Graph 1: {G1} \n Graph 2: {G2} \n")
    print(f" Check lenths:\n seed pair {len(training_seed_pair_list)} \n")
    
    return G1, G2, training_seed_pair_list, test_seed_pair_list


### Now start the main operation 
def main():
    # Get username for PATH default args 
    username = pwd.getpwuid(os.getuid())[0]

    # Set up argument parser
    parser = argparse.ArgumentParser(description="Seed Free Graph Deanonymization Script")
    parser.add_argument('--method_name', type=str, default='pagerank', \
                        help="Method name for centrality or strength measures. Options: 'eigen', 'pagerank', 'degree', 'k-truss', 'k-core'")
    parser.add_argument('--integrate_with_Seed_Based', type=int, choices=[0, 1], default= 1, \
                        help="Set 1 to integrate Seed Based Graph Deanonymization, otherwise 0 for only centrality measures.")
    parser.add_argument('--path', type=str, default= f'/home/{username}/Graph-De-Anonymization/Project_1', \
                        help="Path to the validation dataset or project directory.")
    parser.add_argument('--number_of_top_index_pairs', type=int, default= 50, \
                        help="Before integrating Seed Based method how many top indices pairs you want to provide as given seed pairs")

    args = parser.parse_args()
    
    ### connect with the file paths
    path = args.path
    os.chdir(path)
    print(f"Current Working Directory: {path}")
    # file_path = path + r'\Graph Deanonymization2024\Seed_based'
    file_path = os.path.join(path, 'Graph1', 'validation_Dataset')
 
    train_portion = 0.20
    ecce_threshold = 0.5
    
    G1, G2, training_seed_pair_list, test_seed_pair_list = process_files_and_get_initial_data(file_path,  train_portion = 0.20)
    #r'/content/drive/MyDrive/PhD Academic/Fall 2024/PAC/Project_1/Graph Deanonymization2024/Seed_based'
    # r'F:\Fall 2024\Privacy Aware Computing\Project_1\Graph Deanonymization2024\Graph Deanonymization2024\Seed_based'

    seedFreeAnon = SeedFreeD(G1, G2, training_seed_pair_list, ecce_threshold= ecce_threshold)
    new_seed_pairs, seed_nodes_G1 = seedFreeAnon.iterativeOperation()
    
    
    common = set(new_seed_pairs).intersection(set(test_seed_pair_list)) 
    # num_true_positives = len(common)
    # num_false_positives = len(set(new_seed_pairs) -  set(test_seed_pair_list))
    
    accuracy = len(common)*100 / len(test_seed_pair_list) 
    # precision = num_true_positives*100 / (num_true_positives + num_false_positives)
    # print(f"Accuracy: {accuracy}\t Precision: {precision}")
    print(f"Accuracy: {accuracy}")
    
    with open(path + '//' + 'result_'+ str(train_portion)+'_'+str(ecce_threshold)+'_.txt', 'w') as result_file: 
        result_file.write("Accuracy: "+str(accuracy)+"\n")
        # result_file.write("Precision: "+str(precision)+"\n")
        result_file.close() 
    ### Write newly added seed pairs with given seed pairs in a new file
    with open(path + '//'+'Tanvir_project_1_final_mapping_seed_based.txt', 'w') as final_seed_file:
        for key, value in seed_nodes_G1.items():
            final_seed_file.write(key+' '+seed_nodes_G1[key]+'\n')
        final_seed_file.close()



if __name__ == "__main__":
    main() 

