"""Run records: what code, what input, what environment, what came out.

Implements the policy in `docs/experiment_logging_policy.md`. Read that first --
it says why records are tracked in git while the bytes they describe are not,
and what a record does and does not entitle you to claim.

The short version. A run builds a `RunRecord` before it does any work, because
everything identifying it is known up front; adds its inputs and resolved
configuration; and calls `finish` in a `finally`, so that failed and killed runs
leave records too. `finish` writes an immutable directory under
`results/runs/<run_id>/` and appends one line to `results/runs/index.jsonl`.

Nothing here is Adv-GD specific; the perturbation generator can use it as-is.
"""

from __future__ import annotations

import contextlib
import functools
import hashlib
import io
import json
import os
import platform
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
# One archive for every kind of run -- Adv-GD, pair generation, baseline runs --
# because the questions worth asking cross kinds ("which pair did this run eat,
# and how was that pair made?") and a single ledger answers them with one grep.
# The `kind` field distinguishes them.
ARCHIVE = REPO_ROOT / "results" / "runs"
LEDGER = "index.jsonl"

# Fields a record is not allowed to omit. The first three identify the run; the
# last two exist so that a number can never be quoted without the sample size
# and selection rule it came from -- the policy's one mandatory group.
REQUIRED = ("seed", "status", "note")
REQUIRED_IF_RESTARTS = ("n_restarts", "selection", "selected_seed")

# Excluded from the run id: wall-clock and machine facts, and anything the run
# measured rather than was given. An id has to identify the *question* asked, so
# that a repeat of one configuration is recognisable as a repeat -- including a
# configuration that produced a different answer.
ID_EXCLUDED = frozenset({
    "started_utc", "finished_utc", "seconds", "env", "argv", "note", "status",
    "run_id", "config_sha256", "status_exit", "error", "record_incomplete",
    "metrics", "outputs", "inputs", "supersedes",
    # Measured, not configured.
    "pair_stats", "restarts", "selected_seed", "refine_history",
    "verify_passed", "verify_message", "overwrote_existing", "matchable_nodes",
    "auc_g1", "auc_g2",
})


def _run_git(*args: str, ok: tuple[int, ...] = (0,)) -> str:
    """Return git stdout, or '' if git is unavailable or the call fails.

    `ok` exists because `git diff --no-index` follows diff(1) and exits **1**
    when the files differ, which is the successful case when inlining an
    untracked file. Treating that as a failure silently produced an empty patch
    while reporting nothing wrong.
    """
    try:
        out = subprocess.run(("git", "-C", str(REPO_ROOT)) + args,
                             capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.SubprocessError):
        return ""
    return out.stdout if out.returncode in ok else ""


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()


def sha256_file(path: Path, chunk: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        while block := fh.read(chunk):
            h.update(block)
    return h.hexdigest()


# Untracked content that is archived inline rather than merely hashed. The
# source and the write-ups are what a reader needs to reconstruct a run; data
# and generated bytes are not, and inlining them would put a dataset in the
# patch. Everything excluded is still listed with its digest.
SOURCE_DIRS = ("src/", "docs/", "scripts/")
SOURCE_SUFFIXES = (".py", ".md", ".txt", ".json", ".toml", ".cfg", ".yml", ".yaml", ".sh")
INLINE_MAX_BYTES = 256 * 1024


def describe_file(path: Path, root: Path | None = None) -> dict:
    """Path, size and digest for one artifact, or a note that it is missing."""
    path = Path(path)
    # Posix separators always: a record is text that gets compared and grepped
    # across machines, and a backslash there is not portable.
    rel = (path.relative_to(root).as_posix()
           if root and path.is_relative_to(root) else path.as_posix())
    if not path.exists():
        return {"path": rel, "missing": True}
    return {"path": rel, "bytes": path.stat().st_size, "sha256": sha256_file(path)}


def _summarize_tree(path: Path) -> dict:
    """Describe a directory by its listing instead of its contents.

    Hashing a directory file by file is not viable: the untracked cit-HepTh
    download is 119 MB across ~29,000 files, so walking it would stall every run
    and put 29,000 entries in every record. A digest over (relative path, size)
    pairs detects a changed download at constant cost. It will not notice an
    edit that preserves a file's length, which is an accepted limit -- source,
    where that matters, is inlined in full instead.
    """
    files = sorted(f for f in path.rglob("*") if f.is_file())
    listing = chr(10).join(
        f"{f.relative_to(path).as_posix()} {f.stat().st_size}" for f in files)
    return {
        "path": path.relative_to(REPO_ROOT).as_posix(),
        "tree": True,
        "files": len(files),
        "bytes": sum(f.stat().st_size for f in files),
        "listing_sha256": sha256_text(listing),
    }


def _untracked_source(entries: list[str]) -> tuple[list[str], list[dict]]:
    """Split untracked entries into source files to inline and the rest.

    `git status --porcelain` collapses a wholly untracked directory to one line
    ending in `/`, so an entire new module appears as the single string
    "src/adv_gd/" and none of its contents. Source directories are therefore
    expanded file by file; anything else is summarized by `_summarize_tree`.
    """
    source, other = [], []
    for entry in entries:
        path = REPO_ROOT / entry
        in_source = entry.startswith(SOURCE_DIRS)
        if path.is_dir():
            if in_source:
                source += [f.relative_to(REPO_ROOT).as_posix()
                           for f in sorted(path.rglob("*")) if f.is_file()]
            else:
                other.append(_summarize_tree(path))
        elif in_source:
            source.append(entry)
        else:
            other.append(describe_file(path, REPO_ROOT))
    keep = [f for f in source
            if f.endswith(SOURCE_SUFFIXES)
            and (REPO_ROOT / f).stat().st_size <= INLINE_MAX_BYTES]
    other += [describe_file(REPO_ROOT / f, REPO_ROOT)
              for f in source if f not in keep]
    return keep, other


@functools.lru_cache(maxsize=1)
def git_state() -> tuple[dict, str]:
    """Describe the working tree, and return the uncommitted diff alongside it.

    A commit hash alone misidentifies a dirty tree, which is the normal state
    here -- the whole adv_gd module is uncommitted, so `head` by itself points
    at a tree containing none of the code that produced any of these runs. The
    diff is returned so the caller can archive it: `head` plus that patch
    reconstructs the exact source.

    Cached for the process: a run must not record two different code states for
    itself, and the walk is not free.

    Untracked source files are inlined into the patch; untracked data and
    generated artifacts are listed with digests instead. That boundary is a
    deliberate size tradeoff -- the dataset under `data/` is ~100 MB and a
    record is not a backup -- and it means a record whose untracked inputs were
    data files cannot regenerate them, only detect that they changed.
    """
    head = _run_git("rev-parse", "HEAD").strip()
    branch = _run_git("rev-parse", "--abbrev-ref", "HEAD").strip()
    porcelain = [l for l in _run_git("status", "--porcelain").splitlines() if len(l) > 3]
    dirty = sorted(l[3:].strip().strip('"') for l in porcelain)

    diff = _run_git("diff", "HEAD")
    to_inline, hashed = _untracked_source(
        [l[3:].strip().strip('"') for l in porcelain if l.startswith("??")])
    inlined = []
    for rel in to_inline:
        # --no-index against an empty file renders the whole file as an
        # addition, which is how an untracked file becomes part of a patch.
        # It exits 1 on difference, like diff(1), so that code is accepted.
        extra = _run_git("diff", "--no-index", "--", "/dev/null", rel,
                         ok=(0, 1))
        if extra:
            diff += extra
            inlined.append(rel)
        else:
            hashed.append(describe_file(REPO_ROOT / rel, REPO_ROOT))

    state = {
        "head": head[:12],
        "head_full": head,
        "branch": branch,
        "dirty": bool(dirty),
        "dirty_paths": dirty,
        "untracked_inlined": sorted(inlined),
        "untracked_hashed": hashed,
        "diff_sha256": sha256_text(diff) if diff else None,
        "diff_bytes": len(diff.encode("utf-8", "replace")) if diff else 0,
    }
    return state, diff


def environment() -> dict:
    """Identify the machine and the library builds, not just version numbers.

    Phase 1 trains on CUDA, so a fixed seed is bit-reproducible only against the
    same device and torch build. Recording the build is what makes a later
    mismatch detectable; it cannot make the run portable.
    """
    pkgs = {}
    for name in ("torch", "numpy", "networkx", "scipy", "sklearn"):
        try:
            pkgs[name] = __import__(name).__version__
        except Exception:
            pkgs[name] = None

    cuda = {"available": False}
    try:
        import torch
        cuda["available"] = bool(torch.cuda.is_available())
        if cuda["available"]:
            cuda["device"] = torch.cuda.get_device_name(0)
            cuda["capability"] = ".".join(map(str, torch.cuda.get_device_capability(0)))
            cuda["version"] = torch.version.cuda
    except Exception:
        pass

    return {
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "host": platform.node(),
        "packages": pkgs,
        "cuda": cuda,
        # The inherited baseline is hash-order sensitive and this
        # reimplementation was measured not to be; that claim needs the value
        # it was measured under.
        "hashseed": os.environ.get("PYTHONHASHSEED", "unset"),
    }


class _Tee:
    """Write to the real stream and to a buffer at the same time."""

    def __init__(self, stream, buffer):
        self._stream, self._buffer = stream, buffer

    def write(self, text):
        self._buffer.write(text)
        return self._stream.write(text)

    def flush(self):
        self._stream.flush()

    def __getattr__(self, name):
        return getattr(self._stream, name)


@contextlib.contextmanager
def capture_stderr():
    """Tee stderr into a buffer while leaving it visible on the console.

    The phase modules resolve `sys.stderr` at call time, so replacing it here
    captures their progress output too. A tee rather than a redirect because a
    run takes minutes and watching it is the point; archiving the text is a
    convenience for reading afterwards, never the record -- see rule 5 of the
    policy on why logs are not evidence here.
    """
    buf = io.StringIO()
    saved = sys.stderr
    sys.stderr = _Tee(saved, buf)
    try:
        yield buf
    finally:
        sys.stderr = saved


class RunRecord:
    """One run's record. Build it before the work, finish it in a `finally`."""

    def __init__(self, kind: str, pair: str, status: str, note: str = "",
                 archive: Path = ARCHIVE, argv: list[str] | None = None,
                 supersedes: str | None = None):
        if status not in ("exploratory", "confirmatory"):
            raise ValueError("status must be 'exploratory' or 'confirmatory'; "
                             "set it before the run, not after")
        self.archive = Path(archive)
        self.git, self._diff = git_state()
        self.t0 = time.time()
        self.started = datetime.now(timezone.utc)
        self.data: dict = {
            "kind": kind,
            "pair": pair,
            "status": status,
            "note": note,
            "supersedes": supersedes,
            "started_utc": self.started.isoformat(timespec="seconds"),
            "argv": argv if argv is not None else sys.argv,
            "git": self.git,
            "env": environment(),
            "inputs": [],
            "outputs": [],
            "metrics": {},
        }
        self.run_id = ""      # assigned by seal_id once the config is known
        self._stderr: Path | None = None

    # -- building -------------------------------------------------------------

    def set(self, **fields) -> "RunRecord":
        self.data.update(fields)
        return self

    def metric(self, **fields) -> "RunRecord":
        self.data["metrics"].update(
            {k: v for k, v in fields.items() if v is not None})
        return self

    def add_inputs(self, *paths: Path, root: Path | None = None) -> "RunRecord":
        for p in paths:
            self.data["inputs"].append(describe_file(p, root or REPO_ROOT))
        return self

    def add_outputs(self, *paths: Path, root: Path | None = None) -> "RunRecord":
        for p in paths:
            self.data["outputs"].append(describe_file(p, root or REPO_ROOT))
        return self

    def seal_id(self) -> str:
        """Fix the run id from the code state plus the resolved configuration.

        Called once the configuration is in the record and before any artifact
        is written, so output filenames can carry the id. Two runs differing in
        any recorded input differ in id; a genuine repeat of one configuration
        shows the same trailing hash at a different timestamp.
        """
        if self.run_id:
            return self.run_id
        # Keyed on everything recorded *except* the volatile and the measured,
        # rather than an allow-list of known field names. An allow-list silently
        # ignores whatever a new caller adds: the perturbation generator's beta,
        # mode and node_sample were all invisible to it, so two unrelated
        # generations collided on one id.
        keyed = {k: v for k, v in self.data.items() if k not in ID_EXCLUDED}
        keyed["code"] = (self.git["head_full"], self.git["diff_sha256"])
        keyed["inputs"] = [i.get("sha256") for i in self.data["inputs"]]
        digest = sha256_text(json.dumps(keyed, sort_keys=True, default=str))[:8]
        stamp = self.started.strftime("%Y%m%dT%H%MZ")
        self.run_id = f"{stamp}_{self.data['pair']}_{digest}"
        self.data["run_id"] = self.run_id
        self.data["config_sha256"] = digest
        return self.run_id

    @property
    def dir(self) -> Path:
        return self.archive / self.seal_id()

    # -- finishing ------------------------------------------------------------

    def _validate(self) -> list[str]:
        missing = [k for k in REQUIRED if self.data.get(k) is None]
        if self.data.get("restarts"):
            missing += [k for k in REQUIRED_IF_RESTARTS
                        if self.data.get(k) is None]
        return missing

    def finish(self, status_exit: str = "ok", error: str | None = None,
               stderr_text: str | None = None, verbose: bool = True) -> Path:
        """Write the record directory and append the ledger line.

        Always called, including for a failure or a kill: a run that died in
        Phase 3 is data about where it got to. Validation problems are reported
        and recorded rather than raised, because refusing to write the record of
        a run that has already consumed the compute is the one outcome this
        whole mechanism exists to prevent.
        """
        if status_exit not in ("ok", "error", "killed", "verify_failed"):
            raise ValueError(f"unknown status_exit {status_exit!r}")
        self.data["status_exit"] = status_exit
        if error:
            self.data["error"] = error
        self.data["seconds"] = round(time.time() - self.t0, 1)
        self.data["finished_utc"] = datetime.now(timezone.utc).isoformat(
            timespec="seconds")
        missing = self._validate()
        if missing:
            self.data["record_incomplete"] = missing
            print(f"  record is missing required fields: {missing}",
                  file=sys.stderr)

        out = self.dir
        out.mkdir(parents=True, exist_ok=True)
        if self._diff:
            (out / "diff.patch").write_text(self._diff, encoding="utf-8",
                                            errors="replace")
        if stderr_text:
            (out / "stderr.log").write_text(stderr_text, encoding="utf-8",
                                            errors="replace")

        record = out / "record.json"
        if record.exists():
            # Same configuration, same minute. Do not overwrite a record.
            record = out / f"record.{int(time.time())}.json"
            self.data["note"] = (self.data["note"] +
                                 " [repeat within one minute of an identical "
                                 "configuration; earlier record kept]").strip()
        record.write_text(json.dumps(self.data, indent=2, default=str))

        # The record directory is the authority. Its own ledger line goes
        # there first, so that a lost or garbled shared append costs nothing:
        # `--collate` rebuilds index.jsonl from these. The side ledger is named
        # after the record it describes, not a fixed `ledger.json`, because the
        # immutability guard above may have renamed the record -- a fixed name
        # would let the second run in a directory overwrite the first's line.
        line = self.ledger_line()
        record.with_name(record.name.replace("record", "ledger", 1)).write_text(
            json.dumps(line, indent=2, default=str))

        # Then the shared ledger, best effort. Many cluster array tasks append
        # to this one file; a short single-line O_APPEND write is atomic on a
        # local filesystem but not guaranteed over NFS, so a failure here is
        # reported and not raised -- the run itself succeeded and its record is
        # already on disk.
        self.archive.mkdir(parents=True, exist_ok=True)
        try:
            with open(self.archive / LEDGER, "a", encoding="utf-8") as fh:
                fh.write(json.dumps(line, default=str) + "\n")
        except OSError as exc:
            print(f"  could not append to {LEDGER} ({exc}); run "
                  f"`provenance.py --collate` to rebuild it", file=sys.stderr)

        if verbose:
            print(f"  record {self.run_id}", file=sys.stderr)
        return record

    def ledger_line(self) -> dict:
        """The one-line summary that makes `index.jsonl` greppable."""
        m = self.data["metrics"]
        return {
            "run_id": self.run_id,
            "started_utc": self.data["started_utc"],
            "kind": self.data["kind"],
            "pair": self.data["pair"],
            "status": self.data["status"],
            "status_exit": self.data["status_exit"],
            "seed": self.data.get("seed"),
            "beta": self.data.get("beta"),
            "n_restarts": self.data.get("n_restarts"),
            "anchor_precision": m.get("anchor_precision"),
            "chi": m.get("chi"),
            "gamma": m.get("gamma"),
            "seconds": self.data["seconds"],
            "git": self.git["head"] + ("+dirty" if self.git["dirty"] else ""),
            "note": self.data["note"],
        }


def collate(archive: Path = ARCHIVE, write: bool = True) -> list[dict]:
    """Rebuild index.jsonl from the per-record ledger lines.

    Order is by (started_utc, run_id), which is not the original append order
    when two runs share a timestamp, so do not read position as sequence.

    Run after a cluster sweep, or whenever the shared ledger is suspect. The
    record directories are the source of truth and the ledger is only an index
    over them, so regenerating it is always safe. Records written before
    per-record ledger lines existed are recovered from `record.json` and marked
    `recovered_from_record`, since a field the ledger carried then may be
    missing now.
    """
    lines = []
    # Every record file, not every directory: a directory holds a second
    # `record.<epoch>.json` whenever the immutability guard fired.
    for rec in sorted(Path(archive).glob("*/record*.json")):
        side = rec.with_name(rec.name.replace("record", "ledger", 1))
        if side.exists():
            lines.append(json.loads(side.read_text()))
            continue
        d = json.loads(rec.read_text())
        m = d.get("metrics") or {}
        lines.append({
            "run_id": d.get("run_id"), "started_utc": d.get("started_utc"),
            "kind": d.get("kind"), "pair": d.get("pair"),
            "status": d.get("status"), "status_exit": d.get("status_exit"),
            "seed": d.get("seed"), "beta": d.get("beta"),
            "n_restarts": d.get("n_restarts"),
            "anchor_precision": m.get("anchor_precision"), "chi": m.get("chi"),
            "gamma": m.get("gamma"), "seconds": d.get("seconds"),
            "git": ((d.get("git") or {}).get("head") or "unknown"),
            "note": d.get("note", ""), "recovered_from_record": True,
        })
    # Records with no timestamp (the backfilled ones) sort first, by id. Two
    # lines may share a run_id -- a repeat of an identical configuration within
    # one minute -- and both are kept, because a duplicate id is information.
    lines.sort(key=lambda r: (r.get("started_utc") or "", r.get("run_id") or ""))
    if write:
        (Path(archive) / LEDGER).write_text(
            "".join(json.dumps(l, default=str) + "\n" for l in lines))
    return lines


def read_ledger(archive: Path = ARCHIVE) -> list[dict]:
    """Every ledger line, oldest first. A study is a filter over this."""
    path = Path(archive) / LEDGER
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def _self_test() -> int:
    import tempfile

    git, diff = git_state()
    assert len(git["head_full"]) == 40, "no git head"
    assert isinstance(git["dirty"], bool)
    env = environment()
    assert env["packages"]["torch"], "torch version not captured"
    if not _run_git("ls-files", "src/adv_gd/provenance.py").strip():
        inlined_self = [f for f in git["untracked_inlined"]
                        if f.endswith("provenance.py")]
        assert inlined_self, (
            "this file is untracked but was not inlined into the patch")
        assert "def git_state" in diff, "the patch does not contain this module"
    print(f"  git {git['head']} dirty={git['dirty']} "
          f"({len(git['dirty_paths'])} paths, {len(git['untracked_inlined'])} "
          f"untracked inlined, {len(git['untracked_hashed'])} hashed, "
          f"diff {git['diff_bytes']:,}B)")
    print(f"  env {env['python']} torch {env['packages']['torch']} "
          f"cuda={env['cuda'].get('device', False)}")

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        arch = td / "arch"
        probe = td / "probe.txt"
        probe.write_text("x" * 100)
        d = describe_file(probe, td)
        assert d["bytes"] == 100 and len(d["sha256"]) == 64

        def build(seed=0, note="t"):
            r = RunRecord("selftest", "pair_x", "exploratory", note, archive=arch,
                          argv=["selftest"])
            r.set(seed=seed, params={"dim": 32}, config={"csls_k": 10},
                  restarts=[0.9, 0.8], n_restarts=2, selection="mean_match_cosine",
                  selected_seed=0)
            r.add_inputs(probe, root=td)
            return r

        a, b, c = build(), build(), build(seed=1)
        assert a.seal_id().split("_")[-1] == b.seal_id().split("_")[-1], \
            "identical configurations must share a digest"
        assert a.seal_id().split("_")[-1] != c.seal_id().split("_")[-1], \
            "a changed seed must change the digest"
        assert a.seal_id() == a.seal_id(), "id must be stable once sealed"

        # A field no allow-list knows about must still change the id. This is
        # the collision that hit the perturbation generator.
        odd = build()
        odd.set(beta=0.5, node_sample=0.01)
        assert odd.seal_id().split("_")[-1] != a.seal_id().split("_")[-1], (
            "an unrecognised config field must still affect the run id")
        # ...while a measured outcome must not.
        same = build()
        same.set(verify_passed=False, pair_stats={"overlap_ratio": 0.3})
        assert same.seal_id().split("_")[-1] == a.seal_id().split("_")[-1], (
            "a measured outcome must not affect the run id")

        a.metric(chi=0.913).add_outputs(probe, root=td)
        rec = a.finish(stderr_text="log", verbose=False)
        on_disk = json.loads(rec.read_text())
        assert on_disk["run_id"] == a.run_id
        assert on_disk["metrics"]["chi"] == 0.913
        assert "record_incomplete" not in on_disk, on_disk.get("record_incomplete")
        assert (a.dir / "stderr.log").exists()
        assert (a.dir / "diff.patch").exists() == bool(diff)

        # A second run in the same directory must not clobber the first. Pin the
        # start time rather than relying on the clock staying inside one minute.
        b.started = a.started
        b.run_id = ""
        b.metric(chi=0.5).finish(verbose=False)
        kept = sorted(p.name for p in a.dir.glob("record*.json"))
        assert len(kept) == 2, kept

        # A missing mandatory field is reported, not silently accepted.
        bad = RunRecord("selftest", "pair_x", "exploratory", "n", archive=arch,
                        argv=["x"])
        bad.set(seed=0, restarts=[0.9])
        bad.finish(verbose=False)
        assert "n_restarts" in json.loads(
            (bad.dir / "record.json").read_text())["record_incomplete"]

        with capture_stderr() as buf:
            print("visible and captured", file=sys.stderr)
        assert "visible and captured" in buf.getvalue()
        assert not isinstance(sys.stderr, _Tee), "stderr not restored"

        led = read_ledger(arch)
        assert len(led) == 3, led
        (arch / LEDGER).write_text("garbled" + chr(10))
        rebuilt = collate(arch)
        assert len(rebuilt) == 3, rebuilt
        assert sorted(r["run_id"] for r in rebuilt) == sorted(
            r["run_id"] for r in led), "collate lost or invented a run"
        assert read_ledger(arch) == rebuilt, "collate did not rewrite"
        led = rebuilt
        by_id = {r["run_id"]: r for r in led}
        assert by_id[a.run_id]["chi"] == 0.913
        print(f"  ledger {len(led)} lines, records immutable, validation fires, collate rebuilds")

    print("provenance self-test passed")
    return 0


if __name__ == "__main__":
    if "--collate" in sys.argv:
        rows = collate()
        print(f"rebuilt {ARCHIVE / LEDGER} from {len(rows)} record(s)")
        raise SystemExit(0)
    raise SystemExit(_self_test() if "--self-test" in sys.argv else
                     (print(json.dumps(
                         {"git": git_state()[0], "env": environment()}, indent=2))
                      or 0))
